title: Robert’s blog
url: "https://rcrews.github.io"
author:
  name: Robert Crews
  email: ""
description: >-
  A place to list articles that I've written.

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima
minima:
  skin: auto
  social_links:
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/robertpcrews"
      # title:
    - platform: github
      user_url: "https://github.com/rcrews"
      # title:
    - platform: mastodon
      user_url: "https://norcal.social/@rcrews"
      # title:
    - platform: twitter
      user_url: "https://twitter.com/RobertPCrews"
      # title:
    - platform: facebook
      user_url: "https://www.facebook.com/robert.p.crews"
      # title:

exclude:
  - docs/

# https://github.com/jekyll/jekyll-seo-tag
tagline: ""
social:
  name: Robert Crews
  links:
    - https://twitter.com/RobertPCrews
    - https://www.facebook.com/robert.p.crews
    - https://www.linkedin.com/in/robertpcrews
    - https://github.com/rcrews
    - https://norcal.social/@rcrews
